version: '3.1'

services:
  db:
    build: .
    privileged: true
    container_name: api-db
    restart: always
    tty: true
    ports:
      - '3032:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projectdb
volumes:
  docker:
    driver: local
